version: '2.0'

setEnvironment:
  type: direct

  workflow_meta:
    title:   Setup WFM environment
    author:  NOKIA DEMO
    signature: 01a2c6a2c4d1e330b727755e9c89190a8ceb8c6f72dc7558756f08f4b11e5a2a5aad6a6d550d333b3db124773e8a5b97088272676290bd79a77db4efb3e743b837cdb723133cf6a698696ecfc9ace32611ebbe11a1908fc0e08e4e807067114cf8792fb1075cb5d0a0f25bfc294775a2b0ae36d812536d00a3b92906afdf50c23a25e45e49c1cd5f1df6f0cae8c7a09084471b96be5f559b65bd33be86e894a8291541eff2dacc88945507a5cba53dc2b5c51d4b60604335ebe38bffff371aecabb643b73f5001b74230486dc41b29312d1ab7f9e948e8b1f5dcc51a1a2e330a7c256acff6128a290ef912a6fb985d72f3aa4fd132afb3148382b8e08d3072a4
    version: '1.0.0'
    license: BSD-3
    package: NSP Automation
    deprecated: false
    urls:
      homepage: https://github.com/nokia/nsp-workflow/tree/master/unsupported/wfm/setEnvironment
      repository: https://github.com/nokia/nsp-workflow
      bugs: https://github.com/nokia/nsp-workflow/issues
    dependencies:
      platform:
        nspOS: ['19.6']

  input:
    - token_auth

    - pkiServer: localhost
    - pkiUsername: root
    - pkiPassword: changeme
    - pkiStorepass: 'NokiaNsp1!'

    - mdmServer: localhost
    - mdmUsername: root
    - mdmPassword: changeme

    - wfmServer: localhost
    - wfmUsername: root
    - wfmPassword: changeme

    - mdcServer: localhost
    - mdcPort: 8545

    - neUsername: admin
    - nePassword: admin
    - cflash: cf3

    - certOrg: '/C=CA/ST=Ontario/L=Ottawa/O=Nokia/OU=NSM'
    - certRootCN: '/CN=NSP Development Root CA'
    - certEmail: '/emailAddress=nobody@nokia.com'

  output:
    result: done

  output-on-error:
    result: failed

  tasks:
    createEnvironment:
      action: std.http
      input:
        url: <% locate_nsp("Workflows") %>/v1/action
        method: POST
        verify: False
        headers:
          Content-Type: application/json
          Authorization: Bearer <% $.token_auth %>
        body:
          yaml: |
            version: '2.0'
            environment3:
              description: environment to allow portability of workflows
              base: std.echo
              base-input:
                output: none
              output:
                pkiServer: <% $.pkiServer %>
                pkiUsername: <% $.pkiUsername %>
                pkiPassword: <% $.pkiPassword %>
                pkiStorepass: <% $.pkiStorepass %>
                mdmServer: <% $.mdmServer %>
                mdmUsername: <% $.mdmUsername %>
                mdmPassword: <% $.mdmPassword %>
                wfmServer: <% $.wfmServer %>
                wfmUsername: <% $.wfmUsername %>
                wfmPassword: <% $.wfmPassword %>
                mdcServer: <% $.mdcServer %>
                mdcPort: <% $.mdcPort %>
                neUsername: <% $.neUsername %>
                nePassword: <% $.nePassword %>
                certOrg: <% $.certOrg %>
                certRootCN: <% $.certRootCN %>
                certEmail: <% $.certEmail %>

...
