version: '2.0'

setEnvironment:
  type: direct

  workflow_meta:
    title:   Setup WFM environment
    author:  NOKIA DEMO
    version: '1.0.1'
    license: BSD-3
    package: WFM helpers
    deprecated: false
    urls:
      homepage: https://github.com/nokia/nsp-workflow/tree/master/unsupported/wfm/setEnvironment
      repository: https://github.com/nokia/nsp-workflow
      bugs: https://github.com/nokia/nsp-workflow/issues
    dependencies:
      platform:
        nspOS: ['19.6']

  input:
    - token_auth

    - pkiServer: localhost
    - pkiUsername: root
    - pkiPassword: changeme
    - pkiStorepass: 'NokiaNsp1!'

    - mdmServer: localhost
    - mdmUsername: root
    - mdmPassword: changeme

    - wfmServer: localhost
    - wfmUsername: root
    - wfmPassword: changeme

    - mdcServer: localhost
    - mdcPort: 8545

    - neUsername: admin
    - nePassword: admin
    - cflash: cf3

    - certOrg: '/C=CA/ST=Ontario/L=Ottawa/O=Nokia/OU=NSM'
    - certRootCN: '/CN=NSP Development Root CA'
    - certEmail: '/emailAddress=nobody@nokia.com'

    - nfmpAuthToken: YWRtaW46Tm9raWFOc3AxIQ==

  output:
    result: done

  output-on-error:
    result: failed

  tasks:
    createEnvironment:
      action: std.http
      input:
        url: <% locate_nsp("Workflows") %>/v1/action
        method: POST
        verify: /opt/nsp/os/ssl/certs/nsp/nsp.pem
        headers:
          Content-Type: application/json
          Authorization: Bearer <% $.token_auth %>
        body:
          yaml: |
            version: '2.0'
            environment:
              description: environment to allow portability of workflows
              base: std.echo
              base-input:
                output: none
              output:
                pkiServer: <% $.pkiServer %>
                pkiUsername: <% $.pkiUsername %>
                pkiPassword: <% $.pkiPassword %>
                pkiStorepass: <% $.pkiStorepass %>
                mdmServer: <% $.mdmServer %>
                mdmUsername: <% $.mdmUsername %>
                mdmPassword: <% $.mdmPassword %>
                wfmServer: <% $.wfmServer %>
                wfmUsername: <% $.wfmUsername %>
                wfmPassword: <% $.wfmPassword %>
                mdcServer: <% $.mdcServer %>
                mdcPort: <% $.mdcPort %>
                neUsername: <% $.neUsername %>
                nePassword: <% $.nePassword %>
                cflash: <% $.cflash %>
                certOrg: <% $.certOrg %>
                certRootCN: <% $.certRootCN %>
                certEmail: <% $.certEmail %>
                nfmpAuthToken: <% $.nfmpAuthToken %>

...
