---
version: '2.0'

environment:
  description: create environment to allow portability of workflows
  base: std.echo
  base-input:
    output: none
  output:
    pki_host: localhost
    pki_user: root
    pki_password: changeme
    pki_storepass: 'NokiaNsp1!'
    NEuser: admin
    NEpasswd: admin
